### ISSUE TITLE
responsive="fill" cropping to preserve aspect ratio

### ISSUE THREAD

**Issue by csuydam** [cloudinary/cloudinary-vue#13]
Hello - I'm hoping to handle a situation where the width of my responsive images is a percentage of the page width and the height is set in pixels. I would like to implement responsive Cloudinary images, but it's not maintaining the aspect-ratio, and I can't figure out how to set the crop settings to "fill". I've tried many different crop, width, height and responsive transformation combinations. As an example, the base case would be:

```
<div class="container">
            <cld-image v-bind:publicId="somePublicId" responsive="fill"></cld-image>
</div>

.container {
  width: 20%;
  height: 438px;
}
```

That ends up grabbing the image `http://res.cloudinary.com/hvhp2wfdl/image/upload/c_crop,dpr_2.0,h_636,w_300/v1557949163/product_images/cecilia-bedroom/cecilia-bedroom_hero`
and squishing the width down with CSS. How can I make sure it's grabbing an image with the width of my parent container?

Thank you!

**Comment by arturkulig** [comment]
I'm sorry to say, but you have found an issue that we won't be able to resolve right now.

The width is slightly different because of default breakpoints (from 100 to 4000 with a step of 100). They are there to minimise amount of transformations on the cloud.

The image in my tests is actually not squished (at least not more than due to breakpoints in the works), but rather stretched.

You're absolutely right - `fit` cropping should be picked here and it will be.

I'll keep this issue open until we publish a version with a fix, so you know it is safe to use it.
We are just approaching a new release, so it won't be long now.

**Comment by csuydam** [comment]
Thank you for the quick reply! I'll keep my eye out for the fix
