### ISSUE TITLE
Cannot find module 'current-script-polyfill

### ISSUE THREAD

**Issue by shrestha2lt8** [cloudinary/cloudinary-vue#66]
I am getting below error when I try to use cld-image

Cloudinary.umd.js:242 Uncaught Error: Cannot find module 'current-script-polyfill'
    at webpackMissingModule (Cloudinary.umd.js:242)
    at Object.dc65 (Cloudinary.umd.js:242)
    at __webpack_require__ (Cloudinary.umd.js:30)
    at Module.fb15 (Cloudinary.umd.js:264)
    at __webpack_require__ (Cloudinary.umd.js:30)
    at Cloudinary.umd.js:94
    at Cloudinary.umd.js:97
    at webpackUniversalModuleDefinition (Cloudinary.umd.js:3)
    at Object../node_modules/cloudinary-vue/dist/Cloudinary.umd.js (Cloudinary.umd.js:10)
    at __webpack_require__ (bootstrap:19)

**Comment by mayashavin** [comment]
Which version of `cloudinary-vue` are you using?

**Comment by constructivetim** [comment]
I too started getting this error a few days ago.  "cloudinary-vue": "^1.0.1".

i ran

npm install --save current-script-polyfill

and everything worked again

**Comment by patrick-tolosa** [comment]
It seems 'current-script-polyfill' is a dependency of vue-cli 3.11.0 (that we're using) and is injected by it as a polyfill during the build. 

Since vueCLI internally also ignores all node packages when the build output is a library, it takes a very bold assumption that everyone is using the same vue-cli version. 

In the long run, this will need to be resolved by a build that doesn't assume anything about the installing project.

npm install --save current-script-polyfill will resolve the problem for now, we'll update this thread once we have a more permanent solution.

**Comment by patrick-tolosa** [comment]
Version 1.1.1 should address this issue as now "current-script-polyfill" is part of our dependencies.

Please reopen if this issue persists with the new version
